package com.example.demo;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hibernate entity class for table Star
 * @author MA065202
 * @version 1.0, 10 October 2018 
 */
@Entity
@Table(name="star")
public class Star {

	@Id
	@Column(name="id")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private int id;
	
	@ManyToOne
	@JoinColumn(name="assigned_by")
	private Associate assignedBy;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="assigned_date")
    private Date assignedDate;
	
	@ManyToOne
	@JoinColumn(name="assigned_to")
	private Associate assignedTo;
	
	@Column(name="comment")
	private String comment;
	
	Star(){}
	
	/**
	 * @param id to set id of Star. Auto generated by DBMS
	 * @param assignedBy to set id of an associate who is giving the star
	 * @param assignedDate to set the date and time at which the star is given
	 * @param assignedTo to set id of an associate who is getting the star
	 * @param comment to set any comments for which the star is given.
	 */
	public Star(int id, Associate assignedBy, Date assignedDate, Associate assignedTo, String comment) {
		this.id = id;
		this.assignedBy = assignedBy;
		this.assignedDate = assignedDate;
		this.assignedTo = assignedTo;
		this.comment = comment;
	}
	
	/**
	 * @return id of the star
	 */
	public int getId() {
		return id;
	}
	/**
	 * @param id to set of the star. Auto generated by the DBMS.
	 */
	public void setId(int id) {
		this.id = id;
	}
	/**
	 * @return assignedBy - id of the associate who is giving the star.
	 */
	public Associate getAssignedBy() {
		return assignedBy;
	}
	/**
	 * @param assignedby to set id of the associate who is giving the star
	 */
	public void setAssignedBy(Associate assignedBy) {
		this.assignedBy = assignedBy;
	}
	/**
	 * @return assignedDate and time at which the star is given.
	 */
	public Date getAssignedDate() {
		return assignedDate;
	}
	/**
	 * @param assignedDate to set date and time at which the star is given.
	 */
	public void setAssignedDate(Date assignedDate) {
		this.assignedDate = assignedDate;
	}
	/**
	 * @return assignedTo - id of the associate who is getting the star.
	 */
	public Associate getAssignedTo() {
		return assignedTo;
	}
	/**
	 * @param assignedTo - to set id of the associate who is getting the star.
	 */
	public void setAssignedTo(Associate assignedTo) {
		this.assignedTo = assignedTo;
	}
	/** 
	 * @return comment - for which the star is given to the associate.
	 */
	public String getComment() {
		return comment;
	}
	/**
	 * @param comment to set for which the star is given to the associate.
	 */
	public void setComment(String comment) {
		this.comment = comment;
	}
}